protection:
  required_status_checks:
    strict: false
    contexts: []
  enforce_admins: false
  required_pull_request_reviews:
    dismissal_restrictions:
      users: []
      teams: []
    dismiss_stale_reviews: false
    require_code_owner_reviews: true
    required_approving_review_count: 3
  restrictions:
    users: []
    teams: []
    apps: []
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false
